spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    defer-datasource-initialization: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  security:
    oauth2:
      client:
        registration:
          google: